CREATE OR REPLACE TABLE RETAIL_SALES_CURATED (
    ORDER_ID        STRING,
    ORDER_DATE      DATE,
    PRODUCT         STRING,
    CATEGORY        STRING,
    REGION          STRING,
    QUANTITY        INTEGER,
    SALES_AMOUNT    NUMBER(10,2)
);
