-- Null checks
SELECT COUNT(*) AS NULL_RECORDS
FROM RETAIL_SALES_CURATED
WHERE ORDER_DATE IS NULL
   OR SALES_AMOUNT IS NULL;

-- Duplicate Order IDs
SELECT ORDER_ID, COUNT(*)
FROM RETAIL_SALES_CURATED
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;
