CREATE OR REPLACE VIEW VW_SALES_BY_CATEGORY AS
SELECT
    CATEGORY,
    SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM RETAIL_SALES_CURATED
GROUP BY CATEGORY;

CREATE OR REPLACE VIEW VW_SALES_BY_REGION AS
SELECT
    REGION,
    SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM RETAIL_SALES_CURATED
GROUP BY REGION;


CREATE OR REPLACE VIEW VW_SALES_BY_DATE AS
SELECT
    ORDER_DATE,
    SUM(SALES_AMOUNT) AS DAILY_SALES
FROM RETAIL_SALES_CURATED
GROUP BY ORDER_DATE;
