CREATE OR REPLACE ROLE TABLEAU_READ_ROLE;

GRANT USAGE ON DATABASE RETAIL_DB TO ROLE TABLEAU_READ_ROLE;
GRANT USAGE ON SCHEMA PUBLIC TO ROLE TABLEAU_READ_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO ROLE TABLEAU_READ_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PUBLIC TO ROLE TABLEAU_READ_ROLE;

GRANT ROLE TABLEAU_READ_ROLE TO USER GIRISH;
